### PR TITLE
Fix type error when trying to discover module dependencies for metapackages

### LINKED ISSUE #69: TypeError when using Composer 2.5.6
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.3.0

#### Summary

When using Composer 2.5.6 (see https://github.com/composer/composer/releases/tag/2.5.6) an TypeError occures when using MetaPackages like laminas/laminas-mvc-form

#### Current behavior

An TypeError is thrown

```shell
In ComponentInstaller.php line 754:

  [TypeError]
  Laminas\ComponentInstaller\ComponentInstaller::mapAutoloaders(): Argument #3 ($packagePath) must be of type string, null given, called in ...vendor/laminas/laminas-component-installer/src/ComponentInstaller.php on line 289


Exception trace:
  at ...vendor/laminas/laminas-component-installer/src/ComponentInstaller.php:754
 Laminas\ComponentInstaller\ComponentInstaller->mapAutoloaders() at ...vendor/laminas/laminas-component-installer/src/ComponentInstaller.php:289
 Laminas\ComponentInstaller\ComponentInstaller->loadModuleClassesDependencies() at ...vendor/laminas/laminas-component-installer/src/ComponentInstaller.php:955
 Laminas\ComponentInstaller\ComponentInstaller->addPackageToConfig() at ...vendor/laminas/laminas-component-installer/src/ComponentInstaller.php:218
 Laminas\ComponentInstaller\ComponentInstaller->onPostPackageInstall() at phar://...build/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:206
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://...build/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:148
 Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() at phar://...build/bin/composer.phar/src/Composer/Installer/InstallationManager.php:396
 Composer\Installer\InstallationManager::Composer\Installer\{closure}() at phar://...build/bin/composer.phar/src/Composer/Installer/InstallationManager.php:411
 Composer\Installer\InstallationManager->executeBatch() at phar://...build/bin/composer.phar/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar://...build/bin/composer.phar/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar://...build/bin/composer.phar/src/Composer/Installer.php:797
 Composer\Installer->doInstall() at phar://...build/bin/composer.phar/src/Composer/Installer.php:289
 Composer\Installer->run() at phar://...build/bin/composer.phar/src/Composer/Command/InstallCommand.php:146
 Composer\Command\InstallCommand->execute() at phar://...build/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://...build/bin/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://...build/bin/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://...build/bin/composer.phar/src/Composer/Console/Application.php:378
 Composer\Console\Application->doRun() at phar://...build/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://...build/bin/composer.phar/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar://...build/bin/composer.phar/bin/composer:88
 require() at ...build/bin/composer.phar:29

```

#### How to reproduce

add laminas/laminas-mvc-form and laminas/laminas-component-installer to the composer.json, then run composer install

#### Expected behavior

no TypeError

### PR DESCRIPTION
**Pull request by Xerkus**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
Composer metapackages are not installed same way as other packages. With no install location there is nothing to discover even if metapackage tries to define autoloading rules for whatever reason. No change in effective behavior is introduced.

Starting with composer 2.5.6 the return type for `Composer\Installer\InstallationManager::getInstallPath()` method becomes nullable. This change fixes type error produced for metapackages with defined extras.

Fixes #69

### CODE REVIEW

**Comment by Xerkus** [comment]
I am not sure how to test this. return type is defined as string, so I can't use mocks to force return of null without bumping composer to latest and I don't want to do that because we do not control composer version.

The test for empty install path has no apparent change in behavior, so not sure how to test that one either.

File: src/ComponentInstaller.php [hunk 1]
```diff
@@ -286,6 +286,12 @@ private function loadModuleClassesDependencies(PackageInterface $package): array
         $installer    = $this->composer->getInstallationManager();
         $packagePath  = $installer->getInstallPath($package);
 
+        /** @psalm-suppress TypeDoesNotContainNull Package path become nullable in composer 2.5.6 */
```
Comment (Ocramius) [inline src/ComponentInstaller.php]: Would a `composer.lock` update suffice here, or are we stuck on an older release?

Comment (Ocramius) [reply src/ComponentInstaller.php]: Note: if we can use a newer release, then this requires no test, as it's just a type error, and we can document `$this->mapAutoloaders()` to only accept `non-empty-string`

Comment (Xerkus) [reply src/ComponentInstaller.php]: lock update will suffice but it also brings other issues that would need to be resolved in a separate PR, at that point this becomes unused suppression and can be removed.
On the other hand if I update lock file with only composer/composer only this would work.

lock file maintenance PR did pick up type change:
```
Error: src/ComponentInstaller.php:289:71: PossiblyNullArgument: Argument 3 of Laminas\ComponentInstaller\ComponentInstaller::mapAutoloaders cannot be null, possibly null value provided (see https://psalm.dev/078)
```

**Review by Ocramius — APPROVED** [review]
@Xerkus assuming that removal of your source changes led to psalm picking up the error, and addition of the changes makes the psalm error go away, this is good to :ship:
